class Movie < ActiveRecord::Base
 validates :title, presence: true

 RELEASE_YEAR = [ "1980",
                   "1981",
                   "1982",
                   "1983",
                   "1984",
                   "1985",
                   "1986",
                   "1987",
                   "1988",
                   "1989",
                   "1990",
                   "1991",
                   "1992",
                   "1993",
                   "1994",
                   "1995",
                   "1996",
                   "1997",
                   "1998",
                   "1999",
                   "2000",
                   "2001",
                   "2002",
                   "2003",
                   "2004",
                   "2005",
                   "2006",
                   "2007",
                   "2008",
                   "2009",
                   "2010",
                   "2011",
                   "2012",
                   "2013",
                   "2014"]

  RATING =        [ "10",
                    "9",
                    "8",
                    "7",
                    "6",
                    "5",
                    "4",
                    "3",
                    "2",
                    "1"]

  GENRE =       [ "Action",
                  "Adventure",
                  "Comedy",
                  "Crime",
                  "Fantasy",
                  "Historical",
                  "Horror",
                  "Mystery",
                  "Romance",
                  "Saga",
                  "Thriller"]

end
